parameters:
#    rl_gallery.example.class: RL\GalleryBundle\Example

services:
#    rl_gallery.example:
#        class: %rl_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
