imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
#     host:      %mailer_host%
    username:  symfony.rulinux
    password:  symfony.rulinux

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    
netpositive_discriminator_map:
    discriminator_map:
        thread:
            entity: RL\ForumBundle\Entity\Thread
            children:
                article: RL\ArticlesBundle\Entity\Article
                news: RL\NewsBundle\Entity\News
        section:
            entity: RL\ForumBundle\Entity\Subsection
            children:
                news: RL\NewsBundle\Entity\NewsSubsection

rl_security:
    anonymous:
        class: RL\SecurityBundle\Security\User\AnonymousUser
        defaults: 
            username: anonymous
            enabled: true
            blocks: [Authentication, Links, Gallery, Tracker]

