RLThemesBundle:
    resource: "@RLThemesBundle/Resources/config/routing.yml"
#    resource: "@RLThemesBundle/Controller/"
#    type:     annotation
    prefix:   /

RLMainBundle:
    resource: "@RLMainBundle/Controller/"
    type:     annotation
    prefix:   /

RLSecurityBundle:
    resource: "@RLSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
