RLSecurityBundle:
#         resource: "@RLSecurityBundle/Controller/"
#         type:     annotation
#         prefix:   /
        resource: "@RLSecurityBundle/Resources/config/routing.yml"
        prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#       resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#       prefix:   /_internal

index:
        pattern: /
        defaults: {_controller: RLSecurityBundle:Default:index}

