LorNgDevelopersRulinuxBundle:
    resource: "@LorNgDevelopersRulinuxBundle/Controller/"
    type:     annotation
    prefix:   /
logout:
        pattern: /logout
login:
    pattern:   /login
    defaults:  { _controller: LorNgDevelopersRulinuxBundle:Security:login }
login_check:
    pattern:   /login_check
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
