RLGalleryBundle:
    resource: "@RLGalleryBundle/Controller/"
    type:     annotation
    prefix:   /

RLNewsBundle:
    resource: "@RLNewsBundle/Controller/"
    type:     annotation
    prefix:   /

RLArticlesBundle:
    resource: "@RLArticlesBundle/Controller/"
    type:     annotation
    prefix:   /

RLForumBundle:
    resource: "@RLForumBundle/Controller/"
    type:     annotation
    prefix:   /

RLThemesBundle:
    resource: "@RLThemesBundle/Controller/"
    type:     annotation
    prefix:   /

RLMainBundle:
    resource: "@RLMainBundle/Controller/"
    type:     annotation
    prefix:   /

RLSecurityBundle:
    resource: "@RLSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
