jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
            RL\MainBundle\Entity\User:
              algorithm: md5
              iterations: 1
              encode_as_base64: false

    role_hierarchy:
            ROLE_ADMIN:       [ROLE_MODER, ROLE_ALLOWED_TO_SWITCH]
            ROLE_MODER:       ROLE_USER
            ROLE_ANONYMOUS:   ROLE_USER

    providers:
              chain_provider:
                      chain:
                              providers: [rl_main, db_users]
              rl_main:
                id: rl_main.anonymous.user.provider
              db_users:
                entity: {class: RL\MainBundle\Entity\User, property: username}

    firewalls:

            default:

                pattern: ^/

                form-login:
                    login_path: /login
                    check_path: /login_check

                logout:
                    path: /logout
                    target: /

                remember-me:
                    key: %secret%
                    lifetime: 2592000
                    path: /
                    domain: ~

                rl-anonymous:
                    key: %secret%
                    lifetime: 2592000
                    path: /
                    domain: ~


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
