# src/RL/MainBundle/Resources/config/services.yml
parameters:
  rl_security.anonymous.user.provider.class: RL\SecurityBundle\Security\User\AnonymousUserProvider
  rl_security.anonymous.authentication.listener.class: RL\SecurityBundle\Security\Firewall\AnonymousAuthenticationListener
  rl_security.anonymous.defaults:
  rl_security.anonymous.class:

services:
  rl_security.anonymous.user.provider:
    class: %rl_security.anonymous.user.provider.class%
    arguments:
      - "%rl_security.anonymous.class%"
      - "%rl_security.anonymous.defaults%"
      - "@doctrine"

  rl_security.anonymous.authentication.listener:
    class: %rl_security.anonymous.authentication.listener.class%
    arguments:
      - "@security.context"
      - "@rl_security.anonymous.user.provider"
      - "%rl_security.anonymous.defaults%"
      - "@doctrine"
      - "@?logger"
    tags:
      - {name: monolog.logger, channel: security}
      - {name: kernel.event_listener, event: kernel.response, method: saveUser}
