parameters:
#    rl_forum.example.class: RL\ForumBundle\Example

services:
#    rl_forum.example:
#        class: %rl_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
